spring:
  application:
    name: ums

server:
  port: 8080

billingServiceURL: http://billing/reoccurringPayment
security:
  basic:
    enabled: false
#billingServiceURL: https://billing-semipractical-portfire.apps.cumuluslabs.io/reoccurringPayment